[tox]
envlist = py311, py312, lint, coverage
isolated_build = True   # For package development

[testenv]
# Test dependencies
description = Run unit tests

# extras = None
usedevelop = True

deps =
    pytest
    pytest-cov
    python-dotenv
    polars
    pandas

setenv =
    PYTHONPATH = {toxinidir}{\}src # Makes imports work by adding project root to PYTHONPATH
    ENV = test

commands =
    pytest {posargs}
   
[testenv:coverage]
# Coverage reporting [open report in browser: `>start htmlcov/index.html`]
description = Run tests with coverage reporting

deps =
    {[testenv]deps}

setenv =
    PYTHONPATH = {toxinidir}{\}src
    ENV = test

commands =
    pytest --cov=tabular_nn --cov-report=term-missing --cov-report=html

[testenv:lint]
# Linting environment
description = Run code quality checks (black, ruff, mypy)

deps =
    ruff
    black
    mypy
    pandas-stubs

commands =
    black --check src test
    mypy src
    ruff check src test

[testenv:fast_lint]
# Linting environment
description = Run code quality checks (black, mypy)

deps =
    {[testenv]deps}
    black
    mypy
    pandas-stubs

commands =
    black --check src test
    mypy src

[testenv:black-diff]
# Shows code changes preview
description = Show what black would change without applying

deps =
    black

commands =
    black --diff --color src test

[testenv:format]
# Auto-format code
description = Auto-format code with black and ruff

deps =
    black
    ruff

commands =
    black src test
    ruff check --fix src test

[gh-actions]
python =
    3.11: py311
    3.12: py312